export default[
    {
        id: 1,
        transactionID: '#123354345',
        title: 'Bills - Airtime Recharge',
        provider: 'MTN',
        amount: 'N 20,000',
        status: 'Completed',
        date: '12 Apr 2021',
        tenure: '',
        value: '',
        cardNumber: '',
        bank: '',
        accNumber: ''
    },
    {
        id: 2,
        transactionID: '#123354345',
        title: 'Bills - 20GB Data Subscription',
        provider: 'MTN',
        amount: 'N 25,000',
        status: 'Completed',
        date: '12 Apr 2021',
        tenure: '60 Days',
        value: '',
        cardNumber: '',
        bank: '',
        accNumber: ''
    },
    {
        id: 3,
        transactionID: '#123354345',
        title: 'Bills - Electricity',
        provider: 'KEDCO',
        amount: 'N 25,000',
        status: 'Pending',
        date: '12 Apr 2021',
        tenure: '',
        value: '2,000 KW',
        cardNumber: '',
        bank: '',
        accNumber: '',
        token:'1234 5678 9101 1121'
    },
    {
        id: 4,
        transactionID: '#123354345',
        title: 'Wallet Top Up',
        provider: '',
        amount: 'N 25,000',
        status: 'Completed',
        date: '12 Apr 2021',
        tenure: '',
        value: '',
        cardNumber: '**** **** **** 9283',
        bank: 'GT Bank',
        accNumber: ''
    },
    {
        id: 5,
        transactionID: '#123354345',
        title: 'Printing - Banner',
        provider: '',
        amount: 'N 50,000',
        status: 'Pending',
        date: '12 Apr 2021',
        tenure: '',
        value: '50x50 Ft x 2 Pcs',
        cardNumber: '',
        bank: '',
        accNumber: ''
    },
    {
        id: 6,
        transactionID: '#123354345',
        title: 'Withdrawal',
        provider: '',
        amount: 'N 250,000',
        status: 'Completed',
        date: '12 Apr 2021',
        tenure: '',
        value: '',
        cardNumber: '',
        bank: 'GT Bank',
        accNumber: '0000000000'
    },
]